version: "3.8"

services:
  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    networks:
      - flask-nginx-net

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"   # Expose HTTP
      - "443:443" # Expose HTTPS
    depends_on:
      - flask-app
    networks:
      - flask-nginx-net

networks:
  flask-nginx-net:
    driver: bridge
