version: '3.8'

services:
  nginx:
    image: nginx:latest
    build:
      context: .
    ports:
      - "443:443"
    #volumes:
    #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #  - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app

  app:
    build: ./app
    expose:
      - "3000"