version: '3.8'

services:
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ../PKI_Keys_Gen/intermediateCA/crl:/crl
    depends_on:
      - app

  app:
    build: ./app
    expose:
      - "3000"